export const commonStyles = {
    header: {
        display: "flex",
        justifyContent: "space-between",
        alignItems: "center",
        position: "sticky" as const,
        top: 0,
        background: "var(--vscode-editor-background)",
    },
    headerButtons: {
        display: "flex",
        justifyContent: "space-between",
        alignItems: "center",
    },
    profileList: {
        width: "250px",
        paddingRight: "1rem",
    },
    profileListItem: {
        cursor: "pointer",
        margin: "8px 0",
        padding: "8px",
        borderRadius: "4px",
        border: "2px solid var(--vscode-button-background)",
        position: "relative" as const,
    },
    profileListSelected: {
        backgroundColor: "var(--vscode-button-hoverBackground)",
    },
    profileListUnselected: {
        backgroundColor: "transparent",
    },
    profileName: {
        display: "block",
        overflow: "hidden",
        textOverflow: "ellipsis",
        whiteSpace: "nowrap" as const,
        paddingRight: "24px",
    },
    actionButton: {
        position: "absolute" as const,
        top: "4px",
        right: "4px",
        padding: "2px",
        height: "20px",
        width: "20px",
        display: "flex",
        alignItems: "center",
        justifyContent: "center",
        backgroundColor: "transparent",
        color: "var(--vscode-button-secondaryForeground)",
        borderRadius: "3px",
        cursor: "pointer",
        fontSize: "12px",
        lineHeight: "1",
    },
    dropdownMenu: {
        position: "absolute" as const,
        top: "28px",
        right: "4px",
        backgroundColor: "var(--vscode-dropdown-background)",
        border: "1px solid var(--vscode-dropdown-border)",
        borderRadius: "4px",
        boxShadow: "0 2px 8px rgba(0,0,0,0.15)",
        zIndex: 1000,
        minWidth: "120px",
    },
    dropdownItem: {
        display: "flex",
        alignItems: "center",
        width: "100%",
        padding: "8px 12px",
        border: "none",
        background: "none",
        color: "var(--vscode-dropdown-foreground)",
        cursor: "pointer",
        textAlign: "left" as const,
        fontSize: "12px",
    },
    dropdownItemError: {
        color: "var(--vscode-errorForeground)",
    },
    wizardModal: {
        maxWidth: "600px",
        width: "600px",
        maxHeight: "85vh",
        overflow: "visible",
        display: "flex",
        flexDirection: "column" as const,
        position: "relative" as const,
    },
    wizardContent: {
        flex: 1,
        overflow: "auto",
        paddingRight: "0.5rem",
        position: "relative" as const,
    },
    wizardActions: {
        marginTop: "0.5rem",
        paddingTop: "0.5rem",
        display: "flex",
        justifyContent: "flex-end",
        gap: "0.5rem",
    },
    propertyRow: {
        display: "flex",
        justifyContent: "space-between",
        alignItems: "center",
        minHeight: "32px",
        padding: "4px 0",
    },
    propertyInput: {
        height: "28px",
        fontSize: "0.9em",
        padding: "2px 6px",
        marginBottom: "0",
    },
    secureToggleButton: {
        padding: "0.25rem",
        height: "28px",
        width: "28px",
        display: "flex",
        alignItems: "center",
        justifyContent: "center",
        border: "1px solid var(--vscode-button-border)",
        borderRadius: "4px",
        cursor: "pointer",
        transition: "all 0.2s ease",
        marginLeft: "0.5rem",
    },
    secureToggleButtonActive: {
        backgroundColor: "var(--vscode-button-background)",
        color: "var(--vscode-button-foreground)",
    },
    secureToggleButtonInactive: {
        backgroundColor: "var(--vscode-button-secondaryBackground)",
        color: "var(--vscode-button-secondaryForeground)",
    },
};
