#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

# If not a merge commit, require commit to be signed off
if [ ! -e .git/MERGE_MSG ] && ! grep -q "^Signed-off-by: " "$1"; then
  echo >&2 "Commit message must be signed off with your user name and email."
  echo >&2 "To sign off your commit, add the -s flag to the git commit command."
  exit 1
fi