name: Zowe Explorer Auto Responder for New Issues
# This workflow is triggered when a label is added to an issue.
on:
  issues:
    types: labeled
permissions:
  issues: write

jobs:
  processLabelAction:
    name: Process Label Action
    runs-on: ubuntu-slim
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
        with:
          sparse-checkout: .github

      - name: Process Label Action
        uses: dessant/label-actions@65225c179d3b2502f6eda7b3d15101a3f412366b # v5
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          config-path: '.github/label-actions.yml'
