name: Merge-by

on:
  pull_request:
    types: [opened, ready_for_review]
jobs:
    rfr_add_date:
        name: "Post merge-by date as comment"
        runs-on: ubuntu-slim
        permissions:
            pull-requests: write
        steps:
            - uses: zowe-actions/shared-actions/merge-by@77d7d9b50e60fedc8132b5e5eb6d611c4e483416 # main
              continue-on-error: true
              with:
                operation: "bump-dates"