name: Merge-by

on:
  pull_request:
    types: [opened, ready_for_review]
jobs:
    rfr_add_date:
        name: "Post merge-by date as comment"
        runs-on: ubuntu-22.04
        permissions:
            pull-requests: write
        steps:
            - uses: actions/checkout@v3
            - uses: actions/github-script@v7
              with:
                script: |
                    const script = require("./.github/workflows/merge-by/post-date.js");
                    await script({ github, context });
