name: Merge-by

on:
    pull_request:
      types: [opened, ready_for_review]
    pull_request_review:
      types: [submitted]
    push:
      branches:
        - main
        - next
    workflow_dispatch:
    schedule:
    - cron: "0 11 * * *"
jobs:
    rfr_add_date:
        name: "Build table and notify users"
        runs-on: ubuntu-latest
        permissions:
            discussions: write
            pull-requests: write
        steps:
            - uses: actions/checkout@v3
            - uses: pnpm/action-setup@v4
              with:
                version: 8
                run_install: false

            - uses: actions/setup-node@v4
              with:
                node-version: 22
                cache: 'pnpm'

            - name: Install dependencies
              run: pnpm install

            - uses: actions/github-script@v7
              with:
                script: |
                    const script = require("./.github/workflows/merge-by/build-table-and-notify.js");
                    await script({ github, context });