name: Merge-by

on:
  pull_request:
    types: [opened, ready_for_review]
jobs:
    rfr_add_date:
        name: "Post merge-by date as comment"
        runs-on: ubuntu-22.04
        permissions:
            pull-requests: write
        steps:
            - uses: zowe-actions/shared-actions/merge-by@main
              continue-on-error: true
              with:
                operation: "bump-dates"