# Workflow is disabled until the l10n bug is resolved with re-ordering localized strings. 
name: vscode:prepublish

on: [push, pull_request]

jobs:
  prepare:
    runs-on: ubuntu-latest

    if: (github.event_name == 'push' || github.event.pull_request.head.repo.full_name != github.repository) && !contains(github.event.head_commit.message, '[ci skip]')

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js LTS
        uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - run: |
          npm install -g pnpm@8
          pnpm install

      - name: Check if vscode:prepublish script adds changes
        env:
          CHANGES_DETECTED: "\nChanges detected after running vscode:prepublish. Please run 'pnpm --filter \"vscode-extension-for-zowe\" vscode:prepublish' and commit the changes from the command."
        run: |
          pnpm --filter "vscode-extension-for-zowe" vscode:prepublish
          test -z "$(git status --porcelain)" || { echo $CHANGES_DETECTED; }
          git status
          exit 1